name: flutter_jizhangapp
description: An Account Book App made by Harbin Institute of Technology (Shenzhen) Software Engineering (Fall 2020) Group 19

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  groovin_material_icons: ^1.1.3
  gesture_recognition: ^1.0.1
  shared_preferences: ^0.5.12
  local_auth: ^0.6.3+2
  date_time_picker: ^1.0.2
  introduction_screen: ^1.0.7
    #zzh
  flutter_datetime_picker: ^1.4.0
  toast: ^0.1.3
  sqflite: ^1.3.1
  collection: ^1.14.13
  flutter_picker: ^1.1.5
  smooth_star_rating: ^1.1.1
    #hky
  flutter_staggered_grid_view: ^0.3.2
  date_range_picker: ^1.0.5
  charts_flutter: ^0.9.0
  fl_chart: ^0.11.1
  date_format: ^1.0.9
  flutter_string_encryption: ^0.3.1
  #zxy
  flutter_speed_dial: ^1.2.4
  flutter_slidable: ^0.5.4
  font_awesome_flutter: ^8.10.0
  provider: ^4.0.4
  flutter_swiper : ^1.1.6

  #new
  intl: ^0.16.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - image/tupian.jpg
    - assets/cat_picture.png
    - image/cat.jpg
    - image/homepage1.jpg
    - image/jizhang2.jpg
    - image/tongji3.jpg
    - image/tubiao4.jpg
    - image/login5.jpg
    - image/theme6.jpg
    - image/qingkong7.jpg
    - assets/cat_user.png
    - assets/cat_user1.png
    - image/cat1.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
